runtime: python310

entrypoint: gunicorn Backend.wsgi:application --workers 3 --timeout 300

instance_class: F4

env_variables:
  DJANGO_SETTINGS_MODULE: 'Backend.settings'

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

automatic_scaling:
  max_instances: 1
  min_instances: 1
  min_idle_instances: 1
  max_idle_instances: 1