# Generated by Django 4.1.7 on 2023-03-20 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlantItApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('water_duration', models.IntegerField()),
                ('is_healthy', models.SmallIntegerField()),
                ('optimal_weather', models.CharField(max_length=150)),
                ('water_amount', models.IntegerField(verbose_name=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_watering', models.DateField(verbose_name=6)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlantItApp.plant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='users',
            field=models.ManyToManyField(through='PlantItApp.User_Plants', to=settings.AUTH_USER_MODEL),
        ),
    ]
