# Generated by Django 4.1.7 on 2023-04-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0002_customuser_family_name_customuser_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='family_name',
            new_name='last_name',
        ),
    ]
