# Generated by Django 4.1.7 on 2023-03-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='optimal_weather',
        ),
        migrations.AddField(
            model_name='plant',
            name='maximum_celsius',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='minimum_celsius',
            field=models.IntegerField(default=0),
        ),
    ]
