# Generated by Django 4.1.7 on 2023-03-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_plants',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='user_plants',
            old_name='user_id',
            new_name='user',
        ),
    ]
