# Generated by Django 4.1.7 on 2023-03-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0003_remove_plant_optimal_weather_plant_maximum_celsius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='humidity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='plant',
            name='sun_light',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
