# Generated by Django 4.1.7 on 2023-03-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0003_rename_plant_id_user_plants_plant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_genus',
            name='is_healthy',
        ),
        migrations.AddField(
            model_name='user_plants',
            name='is_healthy',
            field=models.SmallIntegerField(default=1),
        ),
    ]
