# Generated by Django 4.1.7 on 2023-04-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0003_rename_family_name_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
