# Generated by Django 4.1.7 on 2023-03-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0004_plant_humidity_plant_sun_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='plant',
            name='type',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
