# Generated by Django 4.1.7 on 2023-03-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0005_plant_description_plant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='water_amount',
        ),
        migrations.AddField(
            model_name='plant',
            name='water_consumption',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sun_light',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
