# Generated by Django 4.1.7 on 2023-04-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0005_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
    ]
