# Generated by Django 4.1.7 on 2023-03-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0006_remove_plant_water_amount_plant_water_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='is_healthy',
            field=models.SmallIntegerField(default=1),
        ),
    ]
