# Generated by Django 4.1.7 on 2023-04-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0006_alter_customuser_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
