# Generated by Django 4.1.7 on 2023-04-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0007_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
