# Generated by Django 4.1.7 on 2023-04-15 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0010_remove_user_plants_plant_remove_user_plants_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin', models.CharField(max_length=100)),
                ('Family', models.CharField(max_length=150)),
                ('common', models.CharField(max_length=150)),
                ('Category', models.CharField(max_length=40)),
                ('Climate', models.CharField(max_length=30)),
                ('Idealight', models.CharField(max_length=150)),
                ('watering', models.CharField(max_length=300)),
                ('water_duration', models.IntegerField()),
                ('use', models.CharField(max_length=100)),
                ('mincelsius', models.IntegerField(default=0)),
                ('maxcelsius', models.IntegerField(default=20)),
                ('minfahrenheit', models.IntegerField(default=0)),
                ('maxfahrenheit', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_watering', models.DateField(verbose_name=6)),
                ('is_healthy', models.SmallIntegerField(default=1)),
                ('nickname', models.CharField(default=None, max_length=100, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlantItApp.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
