# Generated by Django 4.1.7 on 2023-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0013_plant_toleratedlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_photo',
            field=models.ImageField(default=None, upload_to='plant_photos/'),
            preserve_default=False,
        ),
    ]
