# Generated by Django 4.1.7 on 2023-04-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0016_remove_plant_common_use_common'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='plant',
            field=models.ManyToManyField(related_name='common', to='PlantItApp.plant'),
        ),
        migrations.AlterField(
            model_name='use',
            name='plant',
            field=models.ManyToManyField(related_name='use', to='PlantItApp.plant'),
        ),
    ]
