# Generated by Django 4.1.7 on 2023-05-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0018_userplants_delete_user_plants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPlants',
        ),
    ]
