# Generated by Django 4.1.7 on 2023-05-01 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0019_delete_userplants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=50)),
                ('care', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_watering', models.DateField(verbose_name=6)),
                ('nickname', models.CharField(default=None, max_length=100, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plants', to='PlantItApp.disease')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plants', to='PlantItApp.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
