# Generated by Django 4.1.7 on 2023-05-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantItApp', '0020_disease_userplants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='care',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
