// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOn-57I2HF5CFECA0C8J0I6CfXXipWuho',
    appId: '1:246874156381:android:d55d90e2bb4c2895814cb4',
    messagingSenderId: '246874156381',
    projectId: 'plant-it-app-5c251',
    storageBucket: 'plant-it-app-5c251.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs8fmxU1ypqmtszMssvrWcjeF9e7SCjVY',
    appId: '1:246874156381:ios:6080e975d0fb2efb814cb4',
    messagingSenderId: '246874156381',
    projectId: 'plant-it-app-5c251',
    storageBucket: 'plant-it-app-5c251.appspot.com',
    iosClientId: '246874156381-27qlpli37tc6uq8tihv3idknpogjmli7.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
